# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'account.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(392, 569)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.centralwidget = QtWidgets.QFrame(Dialog)
        self.centralwidget.setStyleSheet("QFrame {\n"
"    border: none;\n"
"}")
        self.centralwidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.centralwidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.main_content = QtWidgets.QFrame(self.centralwidget)
        self.main_content.setStyleSheet("QFrame {\n"
"    border: none;\n"
"}")
        self.main_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_content.setObjectName("main_content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_account = QtWidgets.QFrame(self.main_content)
        self.main_account.setMaximumSize(QtCore.QSize(500, 16777215))
        self.main_account.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.main_account.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_account.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_account.setObjectName("main_account")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_account)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.account_info_div = QtWidgets.QFrame(self.main_account)
        self.account_info_div.setStyleSheet("")
        self.account_info_div.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.account_info_div.setFrameShadow(QtWidgets.QFrame.Raised)
        self.account_info_div.setObjectName("account_info_div")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.account_info_div)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.account_info = QtWidgets.QLabel(self.account_info_div)
        self.account_info.setMinimumSize(QtCore.QSize(0, 130))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.account_info.setFont(font)
        self.account_info.setStyleSheet("color: rgb(46, 52, 54);\n"
"padding-left: 20px;")
        self.account_info.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.account_info.setObjectName("account_info")
        self.verticalLayout_5.addWidget(self.account_info)
        self.verticalLayout_4.addWidget(self.account_info_div)
        self.account_line = QtWidgets.QFrame(self.main_account)
        self.account_line.setMinimumSize(QtCore.QSize(0, 350))
        self.account_line.setMaximumSize(QtCore.QSize(16777215, 700))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.account_line.setFont(font)
        self.account_line.setStyleSheet("QLineEdit{\n"
"    margin-left: 30px;\n"
"    margin-bottom: 20px;\n"
"}\n"
"")
        self.account_line.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.account_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.account_line.setObjectName("account_line")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.account_line)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.account_name = QtWidgets.QLineEdit(self.account_line)
        self.account_name.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.account_name.setFont(font)
        self.account_name.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(46, 82, 101, 200);\n"
"padding-bottom: 10px;")
        self.account_name.setText("")
        self.account_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.account_name.setObjectName("account_name")
        self.verticalLayout_6.addWidget(self.account_name)
        self.account_id = QtWidgets.QLineEdit(self.account_line)
        self.account_id.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.account_id.setFont(font)
        self.account_id.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(46, 82, 101, 200);\n"
"padding-bottom: 10px;")
        self.account_id.setText("")
        self.account_id.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.account_id.setObjectName("account_id")
        self.verticalLayout_6.addWidget(self.account_id)
        self.account_password = QtWidgets.QLineEdit(self.account_line)
        self.account_password.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.account_password.setFont(font)
        self.account_password.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(46, 82, 101, 200);\n"
"padding-bottom: 10px;")
        self.account_password.setText("")
        self.account_password.setFrame(True)
        self.account_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.account_password.setObjectName("account_password")
        self.verticalLayout_6.addWidget(self.account_password)
        self.verticalLayout_4.addWidget(self.account_line, 0, QtCore.Qt.AlignVCenter)
        self.bottom_btns = QtWidgets.QFrame(self.main_account)
        self.bottom_btns.setMaximumSize(QtCore.QSize(16777215, 200))
        self.bottom_btns.setStyleSheet("QFrame {\n"
"    padding-right: 20px;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgba(85, 98, 112, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}")
        self.bottom_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_btns.setObjectName("bottom_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bottom_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.cancel_btn = QtWidgets.QPushButton(self.bottom_btns)
        self.cancel_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.cancel_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(52, 101, 164);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(52, 101, 164);\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_4.addWidget(self.cancel_btn)
        self.confirm_btn = QtWidgets.QPushButton(self.bottom_btns)
        self.confirm_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.confirm_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.confirm_btn.setFont(font)
        self.confirm_btn.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(52, 101, 164);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(52, 101, 164);\n"
"}")
        self.confirm_btn.setObjectName("confirm_btn")
        self.horizontalLayout_4.addWidget(self.confirm_btn)
        self.verticalLayout_4.addWidget(self.bottom_btns)
        self.horizontalLayout_2.addWidget(self.main_account)
        self.horizontalLayout_5.addWidget(self.main_content)
        self.horizontalLayout.addWidget(self.centralwidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.account_info.setText(_translate("Dialog", "계정 정보"))
        self.account_name.setPlaceholderText(_translate("Dialog", "이름"))
        self.account_id.setPlaceholderText(_translate("Dialog", "아이디"))
        self.account_password.setPlaceholderText(_translate("Dialog", "비밀번호"))
        self.cancel_btn.setText(_translate("Dialog", "취소 "))
        self.confirm_btn.setText(_translate("Dialog", "추가"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
