# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nike.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 640)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header.setStyleSheet("")
        self.header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_bar = QtWidgets.QFrame(self.header)
        self.title_bar.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.top_space = QtWidgets.QFrame(self.title_bar)
        self.top_space.setStyleSheet("")
        self.top_space.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_space.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_space.setObjectName("top_space")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.top_space)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.menu_toggle = QtWidgets.QFrame(self.top_space)
        self.menu_toggle.setMaximumSize(QtCore.QSize(55, 16777215))
        self.menu_toggle.setStyleSheet("QFrame{\n"
"    background-color: rgb(27, 29, 35);\n"
"}")
        self.menu_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_toggle.setObjectName("menu_toggle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.menu_toggle)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_btn = QtWidgets.QPushButton(self.menu_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn.sizePolicy().hasHeightForWidth())
        self.menu_btn.setSizePolicy(sizePolicy)
        self.menu_btn.setMinimumSize(QtCore.QSize(10, 5))
        self.menu_btn.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.menu_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn.setIcon(icon)
        self.menu_btn.setIconSize(QtCore.QSize(24, 24))
        self.menu_btn.setFlat(True)
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout_4.addWidget(self.menu_btn)
        self.horizontalLayout_6.addWidget(self.menu_toggle)
        self.title = QtWidgets.QFrame(self.top_space)
        self.title.setStyleSheet("QFrame{\n"
"    background-color: transparent;\n"
"}")
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title.setObjectName("title")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.title)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.title_logo = QtWidgets.QLabel(self.title)
        self.title_logo.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nimbus Sans")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.title_logo.setFont(font)
        self.title_logo.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.title_logo.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"}")
        self.title_logo.setText("")
        self.title_logo.setPixmap(QtGui.QPixmap(":/icons/icons/nike_logo.png"))
        self.title_logo.setObjectName("title_logo")
        self.horizontalLayout_7.addWidget(self.title_logo)
        self.title_name = QtWidgets.QLabel(self.title)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_name.sizePolicy().hasHeightForWidth())
        self.title_name.setSizePolicy(sizePolicy)
        self.title_name.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nimbus Sans")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.title_name.setFont(font)
        self.title_name.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.title_name.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"}")
        self.title_name.setObjectName("title_name")
        self.horizontalLayout_7.addWidget(self.title_name)
        self.horizontalLayout_6.addWidget(self.title, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addWidget(self.top_space)
        self.top_right_btns = QtWidgets.QFrame(self.title_bar)
        self.top_right_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.top_right_btns.setStyleSheet("background-color: rgba(33, 37, 43, 180);\n"
"QPushButton::hover{\n"
"    background-color: rgb(32, 74, 135);\n"
"}\n"
"")
        self.top_right_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_right_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_btns.setObjectName("top_right_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_right_btns)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.restore_btn = QtWidgets.QPushButton(self.top_right_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restore_btn.sizePolicy().hasHeightForWidth())
        self.restore_btn.setSizePolicy(sizePolicy)
        self.restore_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.restore_btn.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.restore_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restore_btn.setIcon(icon1)
        self.restore_btn.setIconSize(QtCore.QSize(16, 16))
        self.restore_btn.setDefault(False)
        self.restore_btn.setFlat(False)
        self.restore_btn.setObjectName("restore_btn")
        self.horizontalLayout_3.addWidget(self.restore_btn)
        self.size_btn = QtWidgets.QPushButton(self.top_right_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.size_btn.sizePolicy().hasHeightForWidth())
        self.size_btn.setSizePolicy(sizePolicy)
        self.size_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.size_btn.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.size_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.size_btn.setIcon(icon2)
        self.size_btn.setIconSize(QtCore.QSize(16, 16))
        self.size_btn.setFlat(False)
        self.size_btn.setObjectName("size_btn")
        self.horizontalLayout_3.addWidget(self.size_btn)
        self.close_btn = QtWidgets.QPushButton(self.top_right_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.close_btn.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.close_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon3)
        self.close_btn.setIconSize(QtCore.QSize(16, 16))
        self.close_btn.setFlat(False)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_3.addWidget(self.close_btn)
        self.horizontalLayout_5.addWidget(self.top_right_btns)
        self.horizontalLayout_2.addWidget(self.title_bar)
        self.verticalLayout.addWidget(self.header)
        self.body = QtWidgets.QFrame(self.centralwidget)
        self.body.setStyleSheet("background-color: rgb(115, 210, 22);")
        self.body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_bar = QtWidgets.QFrame(self.body)
        self.side_bar.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_bar.setFont(font)
        self.side_bar.setStyleSheet("QFrame{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border: none;\n"
"}\n"
"QPushButton{\n"
"    padding: 15px 10px;\n"
"    border: none;\n"
"}\n"
"")
        self.side_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_bar.setObjectName("side_bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_bar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menu_top = QtWidgets.QFrame(self.side_bar)
        self.menu_top.setStyleSheet("")
        self.menu_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_top.setObjectName("menu_top")
        self.formLayout = QtWidgets.QFormLayout(self.menu_top)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.home_btn = QtWidgets.QPushButton(self.menu_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_btn.sizePolicy().hasHeightForWidth())
        self.home_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.home_btn.setFont(font)
        self.home_btn.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icons/icons/cil-home.png);\n"
"    background-repeat: none;\n"
"    background-position: center left;\n"
"    background-color: transparent;\n"
"    padding-top: 20px;\n"
"    padding-left: 30px;\n"
"    border-left: 15px solid rgb(27, 29, 35);\n"
"    text-align: left;\n"
"    color:#fff\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-left: 15px solid rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 15px solid rgb(85, 170, 255);\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-left: 15px solid rgb(33, 37, 43);\n"
"}")
        self.home_btn.setObjectName("home_btn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.home_btn)
        self.account_btn = QtWidgets.QPushButton(self.menu_top)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.account_btn.setFont(font)
        self.account_btn.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icons/icons/cil-user.png);\n"
"    background-repeat: none;\n"
"    background-position: center left;\n"
"    background-color: transparent;\n"
"    padding-top: 20px;\n"
"    padding-left: 30px;\n"
"    border-left: 15px solid rgb(27, 29, 35);\n"
"    text-align: left;\n"
"    color:#fff\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-left: 15px solid rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 15px solid rgb(85, 170, 255);\n"
"}")
        self.account_btn.setObjectName("account_btn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.account_btn)
        self.verticalLayout_2.addWidget(self.menu_top)
        self.settings_btn = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.settings_btn.setFont(font)
        self.settings_btn.setStyleSheet("QPushButton{\n"
"    background-image: url(:/icons/icons/cil-settings.png);\n"
"    background-repeat: none;\n"
"    background-position: center left;\n"
"    background-color: transparent;\n"
"    padding-top: 20px;\n"
"    padding-left: 30px;\n"
"    border-left: 15px solid rgb(27, 29, 35);\n"
"    text-align: left;\n"
"    color:#fff\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-left: 15px solid rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 15px solid rgb(85, 170, 255);\n"
"}")
        self.settings_btn.setObjectName("settings_btn")
        self.verticalLayout_2.addWidget(self.settings_btn)
        self.horizontalLayout.addWidget(self.side_bar)
        self.main_item = QtWidgets.QFrame(self.body)
        self.main_item.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.main_item.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_item.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_item.setObjectName("main_item")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_item)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_item)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setStyleSheet("")
        self.home_page.setObjectName("home_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.home_page)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.home_page)
        self.account_page = QtWidgets.QWidget()
        self.account_page.setStyleSheet("")
        self.account_page.setObjectName("account_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.account_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.account_content = QtWidgets.QFrame(self.account_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.account_content.setFont(font)
        self.account_content.setStyleSheet("background-color: #718093;")
        self.account_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.account_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.account_content.setObjectName("account_content")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.account_content)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.acount_list = QtWidgets.QFrame(self.account_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acount_list.sizePolicy().hasHeightForWidth())
        self.acount_list.setSizePolicy(sizePolicy)
        self.acount_list.setMinimumSize(QtCore.QSize(300, 0))
        self.acount_list.setMaximumSize(QtCore.QSize(700, 16777215))
        self.acount_list.setStyleSheet("QFrame {\n"
"    border:none;\n"
"}")
        self.acount_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.acount_list.setFrameShadow(QtWidgets.QFrame.Raised)
        self.acount_list.setObjectName("acount_list")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.acount_list)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.account_title_div = QtWidgets.QFrame(self.acount_list)
        self.account_title_div.setMinimumSize(QtCore.QSize(0, 70))
        self.account_title_div.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.account_title_div.setFrameShadow(QtWidgets.QFrame.Raised)
        self.account_title_div.setObjectName("account_title_div")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.account_title_div)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.account_title = QtWidgets.QLabel(self.account_title_div)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.account_title.setFont(font)
        self.account_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.account_title.setStyleSheet("padding-top: 10px;")
        self.account_title.setAlignment(QtCore.Qt.AlignCenter)
        self.account_title.setObjectName("account_title")
        self.verticalLayout_8.addWidget(self.account_title)
        self.verticalLayout_7.addWidget(self.account_title_div)
        self.account_table_div = QtWidgets.QFrame(self.acount_list)
        self.account_table_div.setStyleSheet("background-color: rgb(39, 44, 54);\n"
"border-radius: 7px;")
        self.account_table_div.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.account_table_div.setFrameShadow(QtWidgets.QFrame.Raised)
        self.account_table_div.setObjectName("account_table_div")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.account_table_div)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.account_table = QtWidgets.QTableWidget(self.account_table_div)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_table.sizePolicy().hasHeightForWidth())
        self.account_table.setSizePolicy(sizePolicy)
        self.account_table.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.account_table.setFont(font)
        self.account_table.setAccessibleDescription("")
        self.account_table.setStyleSheet("QTableWidget {    \n"
"    background-color: rgb(39, 44, 54);\n"
"    padding: 10px;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"QTableWidget::item{\n"
"    border-top: 15px solid rgb(39, 44, 54);\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    background-color: rgb(39, 44, 54);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    max-width: 30px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 25px;\n"
"    margin: 20px 0 20px 10px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    margin-top: 20px;\n"
"    border-radius: 7px;\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    margin-top : 10px;\n"
"    margin-left: 10px;\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    margin-left: 10px;\n"
"    margin-top: 20px;\n"
"    height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"")
        self.account_table.setInputMethodHints(QtCore.Qt.ImhNone)
        self.account_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.account_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.account_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.account_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.account_table.setAutoScroll(True)
        self.account_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.account_table.setDragDropOverwriteMode(True)
        self.account_table.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.account_table.setAlternatingRowColors(False)
        self.account_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.account_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.account_table.setTextElideMode(QtCore.Qt.ElideRight)
        self.account_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.account_table.setShowGrid(False)
        self.account_table.setGridStyle(QtCore.Qt.SolidLine)
        self.account_table.setObjectName("account_table")
        self.account_table.setColumnCount(4)
        self.account_table.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.account_table.setHorizontalHeaderItem(3, item)
        self.account_table.horizontalHeader().setVisible(True)
        self.account_table.horizontalHeader().setCascadingSectionResizes(True)
        self.account_table.horizontalHeader().setHighlightSections(False)
        self.account_table.horizontalHeader().setMinimumSectionSize(50)
        self.account_table.horizontalHeader().setSortIndicatorShown(False)
        self.account_table.horizontalHeader().setStretchLastSection(False)
        self.account_table.verticalHeader().setVisible(True)
        self.account_table.verticalHeader().setCascadingSectionResizes(False)
        self.account_table.verticalHeader().setHighlightSections(False)
        self.account_table.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_11.addWidget(self.account_table)
        self.verticalLayout_7.addWidget(self.account_table_div)
        self.account_bottom = QtWidgets.QFrame(self.acount_list)
        self.account_bottom.setMinimumSize(QtCore.QSize(0, 45))
        self.account_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.account_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.account_bottom.setObjectName("account_bottom")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.account_bottom)
        self.horizontalLayout_10.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_10.setSpacing(8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.account_delete_btn = QtWidgets.QPushButton(self.account_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_delete_btn.sizePolicy().hasHeightForWidth())
        self.account_delete_btn.setSizePolicy(sizePolicy)
        self.account_delete_btn.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.account_delete_btn.setFont(font)
        self.account_delete_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;    \n"
"    background-color: #e74c3c;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(204, 0, 0);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(204, 0, 0);\n"
"}\n"
"")
        self.account_delete_btn.setObjectName("account_delete_btn")
        self.horizontalLayout_10.addWidget(self.account_delete_btn)
        self.account_edit_btn = QtWidgets.QPushButton(self.account_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_edit_btn.sizePolicy().hasHeightForWidth())
        self.account_edit_btn.setSizePolicy(sizePolicy)
        self.account_edit_btn.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.account_edit_btn.setFont(font)
        self.account_edit_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.account_edit_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;    \n"
"    background-color: #2980b9;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 101, 164);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(52, 101, 164);\n"
"}")
        self.account_edit_btn.setObjectName("account_edit_btn")
        self.horizontalLayout_10.addWidget(self.account_edit_btn)
        self.account_create_btn = QtWidgets.QPushButton(self.account_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_create_btn.sizePolicy().hasHeightForWidth())
        self.account_create_btn.setSizePolicy(sizePolicy)
        self.account_create_btn.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.account_create_btn.setFont(font)
        self.account_create_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;    \n"
"    background-color: #2980b9;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 101, 164);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(52, 101, 164);\n"
"}\n"
"")
        self.account_create_btn.setObjectName("account_create_btn")
        self.horizontalLayout_10.addWidget(self.account_create_btn)
        self.verticalLayout_7.addWidget(self.account_bottom)
        self.horizontalLayout_8.addWidget(self.acount_list)
        self.verticalLayout_4.addWidget(self.account_content)
        self.stackedWidget.addWidget(self.account_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.settings_page.setObjectName("settings_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.settings_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.settings_page)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.settings_page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.main_item)
        self.verticalLayout.addWidget(self.body)
        self.footer = QtWidgets.QFrame(self.centralwidget)
        self.footer.setMaximumSize(QtCore.QSize(16777215, 25))
        self.footer.setStyleSheet("background-color: rgb(52, 101, 164);\n"
"QFrame{\n"
"    border: none;\n"
"}")
        self.footer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.left_menu_bottom = QtWidgets.QFrame(self.footer)
        self.left_menu_bottom.setMinimumSize(QtCore.QSize(55, 0))
        self.left_menu_bottom.setStyleSheet("QFrame{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border:none;\n"
"}")
        self.left_menu_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_bottom.setObjectName("left_menu_bottom")
        self.horizontalLayout_9.addWidget(self.left_menu_bottom, 0, QtCore.Qt.AlignLeft)
        self.version_label = QtWidgets.QLabel(self.footer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.version_label.setFont(font)
        self.version_label.setStyleSheet("margin: 5px 2px 3px;")
        self.version_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_label.setObjectName("version_label")
        self.horizontalLayout_9.addWidget(self.version_label)
        self.window_size_grip = QtWidgets.QFrame(self.footer)
        self.window_size_grip.setMaximumSize(QtCore.QSize(20, 16777215))
        self.window_size_grip.setStyleSheet("border: none;")
        self.window_size_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_size_grip.setObjectName("window_size_grip")
        self.horizontalLayout_9.addWidget(self.window_size_grip)
        self.verticalLayout.addWidget(self.footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p><p><br/></p></body></html>"))
        self.title_name.setText(_translate("MainWindow", " NIKE BOT"))
        self.home_btn.setText(_translate("MainWindow", "Home"))
        self.account_btn.setText(_translate("MainWindow", "Account"))
        self.settings_btn.setText(_translate("MainWindow", "Settings"))
        self.label.setText(_translate("MainWindow", "HOME"))
        self.account_title.setText(_translate("MainWindow", "계정 목록      "))
        self.account_table.setSortingEnabled(False)
        item = self.account_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.account_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ver"))
        item = self.account_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "이름"))
        item = self.account_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "아이디"))
        item = self.account_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "비밀번호"))
        self.account_delete_btn.setText(_translate("MainWindow", "삭제"))
        self.account_edit_btn.setText(_translate("MainWindow", "수정"))
        self.account_create_btn.setText(_translate("MainWindow", "추가"))
        self.label_3.setText(_translate("MainWindow", "STEEINGS"))
        self.footer.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p><p><br/></p></body></html>"))
        self.version_label.setText(_translate("MainWindow", "v 1.0.0"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
